---
title: "Análisis preliminar"
output: pdf_document
---


```{r global-options, include=FALSE}
knitr::opts_chunk$set(echo=F, warning=FALSE, message=FALSE,collapse=TRUE,fig.align="center",fig.pos="h!")
```


```{r results='hide'}
## Librerías requeridas
 paquetes <- c("stringr", "tidyverse", "kableExtra","ggplot2","ggthemes",
               "patchwork","dplyr","reshape","here","pdftools","ggpubr","tidyr")
 lapply(paquetes, require, character.only = TRUE)
 
```


```{r echo=FALSE}
## Directorios de trabajo
dir.0   <- here() 
dir.s0   <- here("codigo_admb_modificado") 
dir.fun <- here("funciones") 
#dir.Rdata<-here("Rdata","Esc_CVcru")

```


```{r echo=FALSE}
## Cargar funciones
source(here(dir.fun,"functions.R")) 
source(here(dir.fun,"Fn_CrearRdata.R"))
source(here(dir.fun,"Fn_Data.frame.R"))
source(here(dir.fun,"Fn_Figuras.R"))
source(here(dir.fun,"Fn_Tablas.R"))
source(here(dir.fun,"Fn_PBRs.R")) 
source(here(dir.fun,"removefile.R"))										   									
```

# Revisión de los datos

```{r eval=FALSE, include=F}
## Compilar y ejecutar modelo ADMB
setwd(dir.s0)
#para mac
system("~/admb-12.2/admb MAE323")
system("./MAE323")

source(here("funciones","removefile.R"))
removefileadmb(dir.s0,"MAE323") 

```

```{r}
data1        <- lisread(here("codigo_admb_modificado","MAE323.dat")) 
names(data1) <- str_trim(names(data1), side="right")
dat1         <- data1
```

```{r}
Datos<-dat1$Ind %>% data.frame()
names(Datos)<-c("year","reclas","cv_R","pelaces","cv_P","mpdh","cv_M","desembarque","cv_D")
kbl(Datos)
```



```{r}
Datos1<-Datos[,c(1,2,4,6,8)] %>% melt(id="year")

ggplot(Datos1,aes(x=year,y=value/1000000))+
  geom_area(aes(color=variable,fill=variable),alpha=.3)+
  ylab("Biomasas (millones de t)")+xlab("Años")+ggtitle("Sardina común")+
  theme_bw()
  

 ```
```


```{r}
rep1         <- reptoRlist("MAE0921.rep")